AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend deployment para proyecto de clase (Lambdas vacías)

Parameters:
  DBUsername:
    Type: String
    Default: admingestor
  DBPassword:
    Type: String
    NoEcho: true
  LabRoleArn:
    Type: String
    Description: ARN del LabRole existente de IAM que se usará para las funciones Lambdas.

Resources:
  
  # Base de datos RDS PostgreSQL
  #BackendDB:
  #  Type: AWS::RDS::DBInstance
  #  Properties:
  #    DBName: backenddb
  #    Engine: postgres
  #    #EngineVersion: "18.1"
  #    EngineVersion: "16.3"
  #    MasterUsername: !Ref DBUsername
  #    MasterUserPassword: !Ref DBPassword
  #    DBInstanceClass: db.t3.micro
  #    AllocatedStorage: 20
  #    PubliclyAccessible: false

  # Colas SQS
  Queue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: queue-1

  Queue2:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: queue-2

  # Lambda 1 (vacía) con API Gateway
  Lambda1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Lambda1
      Runtime: python3.12
      Handler: index.lambda_handler
      InlineCode: |
        def lambda_handler(event, context):
            pass
      Role: !Ref LabRoleArn
      Events:
        CrearPost:
          Type: Api
          Properties:
            Path: /crear
            Method: post
        ConsultarGet:
          Type: Api
          Properties:
            Path: /consultar
            Method: get

  # Lambda 2 (vacía) con trigger SQS1
  BackendCalculos:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BackendCalculos
      Runtime: python3.12
      Handler: lambda2.lambda_handler
      CodeUri: ../src/backend/
      Policies:                        # permisos para escribir en la siguiente cola
        - SQSSendMessagePolicy:
            #QueueName: !GetAtt Queue2.QueueName
            QueueName: queue-2
      Environment:                  
        Variables:
          # DB_HOST: !GetAtt BackendDB.Endpoint.Address
          # DB_NAME: backenddb
          # DB_USER: !Ref DBUsername
          # DB_PASSWORD: !Ref DBPassword
          QUEUE_2_URL: !Ref Queue2
      Role: !Ref LabRoleArn
      Events:
        QueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue1.Arn
            BatchSize: 1               # Procesa los mensajes de uno en uno para evitar errores

  # Lambda 3 con trigger SQS2
  BackendGeneracionDocumentos:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BackendDocumentos
      Runtime: python3.12
      CodeUri: ../src/backend/
      Handler: lambda3.lambda_handler
      Role: !Ref LabRoleArn
      Environment:                  
        Variables:
          BUCKET_NAME: !Sub "facturas-gestorsiniestros-${AWS::AccountId}"
          #DB_HOST: !GetAtt BackendDB.Endpoint.Address
          #DB_NAME: backenddb
          #DB_USER: !Ref DBUsername
          #DB_PASSWORD: !Ref DBPassword
      Policies:
        - S3WritePolicy:
            BucketName: !Sub "facturas-gestorsiniestros-${AWS::AccountId}"
      Events:
        QueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue2.Arn